apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sketchfront
  labels: 
    app: sketchfront
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sketchfront
  template: 
    metadata:
      labels: 
        app: sketchfront
    spec:
      containers:
      - name: frontend
        image: kumarnitesh2000/sketch_frontend:1e9a971
        ports:
        - containerPort: 5000
          
        
