apiVersion: v1
kind: Service
metadata:
  name: sketch-service
spec:
  type: NodePort
  #or type: LoadBalancer
  selector:
    app: sketch
  ports:
  - protocol: TCP
    port: 5000 
    targetPort: 5000
