apiVersion: v1
kind: Service
metadata:
  name: sketchfrontend
spec:
  type: LoadBalance
  #or type: NodePort
  selector:
    app: sketch
  ports:
  - protocol: TCP
    port: 5000 
    targetPort: 5000