apiVersion: v1
kind: Service
metadata:
  name: sketchfrontend
spec:
  type: LoadBalancer
  #or type: NodePort
  selector:
    app: sketchfront
  ports:
  - protocol: TCP
    port: 5000 
    targetPort: 5000
