apiVersion: v1
kind: Service
metadata:
  name: sketchfront
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: sketchfront
  ports:
  - protocol: TCP
    port: 5000 
    targetPort: 5000
