apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sketch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kumarnitesh2000/kubManifest.git
    targetRevision: HEAD
    path: /sketch-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sketch
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
