apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sketch
  name: sketchdepl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sketch
  template:
    metadata:
      labels:
        app: sketch
    spec:
      containers:
      - env:
        - name: link
          valueFrom:
            configMapKeyRef:
              key: link
              name: sketch-config
        image: kumarnitesh2000/sketch_backend:648ab9a
        name: sketch
        ports:
        - containerPort: 5000
      - image: redis
        name: redispy
        volumeMounts:
        - mountPath: /data
          name: pv-hostpath
      volumes:
      - name: pv-hostpath
        persistentVolumeClaim:
          claimName: pvchostpath
